// Ref: PRD §6.4 — Word DOCX export using docx npm library

import {
  Document, Packer, Paragraph, Table, TableRow, TableCell,
  TextRun, HeadingLevel, AlignmentType, WidthType, BorderStyle,
  ShadingType,
} from "docx";
import type { BomExport } from "./bom-schema";
import type { Project } from "@/lib/store";

function heading1(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_1, spacing: { before: 400, after: 200 } });
}

function heading2(text: string): Paragraph {
  return new Paragraph({ text, heading: HeadingLevel.HEADING_2, spacing: { before: 300, after: 150 } });
}

function para(text: string, bold = false): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, bold, size: 20 })],
    spacing: { after: 100 },
  });
}

function kvPara(label: string, value: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 20 }),
      new TextRun({ text: value, size: 20 }),
    ],
    spacing: { after: 80 },
  });
}

function bomTable(items: BomExport["items"]): Table {
  const headers = ["Item", "Category", "Qty", "Unit Price (USD)", "Total (USD)"];
  const headerRow = new TableRow({
    children: headers.map((h) =>
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: h, bold: true, size: 18 })] })],
        shading: { type: ShadingType.SOLID, color: "EEF2FF" },
        width: { size: 20, type: WidthType.PERCENTAGE },
      })
    ),
  });

  const dataRows = items.map((item) =>
    new TableRow({
      children: [
        new TableCell({ children: [new Paragraph(item.name)] }),
        new TableCell({ children: [new Paragraph(item.category)] }),
        new TableCell({ children: [new Paragraph(String(item.quantity))] }),
        new TableCell({ children: [new Paragraph(item.unitPriceUsd ? `$${item.unitPriceUsd.toLocaleString()}` : "—")] }),
        new TableCell({ children: [new Paragraph(item.totalPriceUsd ? `$${item.totalPriceUsd.toLocaleString()}` : "—")] }),
      ],
    })
  );

  return new Table({
    rows: [headerRow, ...dataRows],
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top:          { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      bottom:       { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      left:         { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      right:        { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
      insideVertical:   { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
    },
  });
}

export async function buildDocx(project: Project, bom: BomExport): Promise<Buffer> {
  const s = bom.sizing;
  const now = new Date(bom.generatedAt).toLocaleDateString("en-US", { dateStyle: "long" });

  const doc = new Document({
    title: `${project.name} — ML Sizing Report`,
    description: "Generated by ML Sizer",
    sections: [
      {
        children: [
          // Cover / Title
          new Paragraph({
            children: [new TextRun({ text: project.name, bold: true, size: 48 })],
            alignment: AlignmentType.LEFT,
            spacing: { after: 200 },
          }),
          para("ML/GenAI Inference Sizing Report"),
          kvPara("Customer",  project.customer || "—"),
          kvPara("Generated", now),
          ...(project.description ? [para(project.description)] : []),

          // Executive Summary
          heading1("Executive Summary"),
          para(
            `This report presents the infrastructure sizing for ${project.name}. ` +
            `The sizing engine has determined the recommended hardware configuration based on ` +
            `workload requirements, model architecture, and performance targets.`
          ),

          // Sizing Highlights
          ...(s ? [
            heading1("Sizing Highlights"),
            kvPara("GPU",              `${s.totalGpus}× ${s.gpuModel}`),
            kvPara("Servers",          `${s.serverCount}`),
            kvPara("Replicas",         `${s.replicas}`),
            kvPara("Power Draw",       `${s.powerKw.toFixed(1)} kW`),
            kvPara("Rack Units",       `${s.rackUnits}U`),
            kvPara("TTFT (est.)",      `${s.ttftMs.toFixed(0)} ms`),
            kvPara("End-to-End P95",   `${s.endToEndMs.toFixed(0)} ms`),
            kvPara("Inference Server", s.inferenceServer),
          ] : []),

          // Workload Parameters
          heading1("Workload Parameters"),
          kvPara("Model",             project.discovery.model.name || "—"),
          kvPara("Parameters",        `${project.discovery.model.params}B`),
          kvPara("Quantization",      project.discovery.model.quantization),
          kvPara("Context Length",    `${project.discovery.model.contextLength.toLocaleString()} tokens`),
          kvPara("Concurrent Users",  `${project.discovery.load.concurrentUsers}`),
          kvPara("Avg Input Tokens",  `${project.discovery.load.avgInputTokens}`),
          kvPara("Avg Output Tokens", `${project.discovery.load.avgOutputTokens}`),
          kvPara("P95 Target",        `${project.discovery.load.targetLatencyP95Ms} ms`),

          // Bill of Materials
          heading1("Bill of Materials"),
          bomTable(bom.items),
          new Paragraph({ spacing: { before: 200, after: 100 } }),
          kvPara("Total CapEx (Est.)", bom.totals.capexUsd > 0 ? `$${bom.totals.capexUsd.toLocaleString()}` : "—"),

          // Disclaimers
          heading1("Assumptions & Disclaimers"),
          para(
            "Sizing estimates are based on analytical models and published benchmark data. " +
            "Actual performance may vary based on workload characteristics, software versions, " +
            "and deployment configuration. Pricing reflects list prices and may not include " +
            "discounts, support contracts, or installation costs. " +
            "This report is intended for planning purposes only and should be validated against vendor quotes."
          ),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}
